apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sarenakh.fullname" . }}
  labels:
    {{- include "sarenakh.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
  COOKIE_SECURE: {{ include "sarenakh.cookieSecure" . | quote }}
  DATA_DIR: "/app/data"
